function [] = plot_mcmc_kinetics()

    %%% command:
    %%% plot_mcmc_kinetics()  
   
    clc;
    close all
    set(0,'DefaultFigureVisible','on');
        
    metadata = load('datamat.mat');
         
    Rif = {1,10};
    vars = [2,3,4,7,8,9,10,12,13,14,15];
    data = {{[]};...
            metadata.data_deg;...
            {[]};... 
            {[]};... 
            metadata.data_l;...
            {[]};...   
            metadata.data_h;
            };
    stdev = {{[]};...
             metadata.stdev_deg;...
             {[]};... 
             {[]};... 
             metadata.stdev_l;...
             {[]};... 
             metadata.stdev_h
             };
    time = {[];...
            metadata.time_deg;...
            metadata.time_deg;...
            metadata.time_deg;...
            [];...
            [];...
            metadata.time_l;...
            metadata.time_l;...
            metadata.time_l;...
            metadata.time_l;...
            [];...
            metadata.time_h;...
            metadata.time_h;...
            metadata.time_h;...
            metadata.time_h
            };
    tmax = {metadata.tmax_l;...
            metadata.tmax_h};      
    T = {[],...
         metadata.t_deg,...
         metadata.t_deg,...
         metadata.t_deg,...
         [],...
         metadata.t_l,...
         metadata.t_l,...
         metadata.t_l,...
         metadata.t_l,...
         metadata.t_l,...
         metadata.t_h,...
         metadata.t_h,...
         metadata.t_h,...
         metadata.t_h,....
         metadata.t_h
         };        
    timeXaxis = {[];...
                 [0,12,24,36,48];...
                 [0,12,24,36,48];...
                 [0,12,24,36,48];...
                 [];...
                 [0,24,48,72,120,168];...
                 [0,24,48,72,120,168];...
                 [0,24,48,72,120,168];...
                 [0,24,48,72,120,168];...
                 [0,24,48,72,120,168];...
                 [0,24,48,72,120,168,240];...
                 [0,24,48,72,120,168,240];...
                 [0,24,48,72,120,168,240];...
                 [0,24,48,72,120,168,240];...
                 [0,24,48,72,120,168,240]
                 };
    YLims = {[];...
             [-0.1 1.1];...
             [-0.1 1.1];...
             [-0.1 1.1];...
             [];...
             [-0.1 1.1];...
             [0.4 7.6];...
             [0.4 7.6];...
             [0.4 7.6];...
             [0.4 7.6];...
             [-0.1 1.1];...
             [0.4 7.6];...
             [0.4 7.6];...
             [0.4 7.6];...
             [0.4 7.6]
             };    
    YTick = {[];...
             0:0.2:1;...
             0:0.2:1;...
             0:0.2:1;...
             [];...
             0:0.2:1;...
             1:2:7;...
             1:2:7;...
             1:2:7;...
             1:2:7;...
             0:0.2:1;...
             1:2:7;...
             1:2:7;...
             1:2:7;...
             1:2:7
             };    
    YTickLabel = {{};...
                  {'0','0.2','0.4','0.6','0.8','1.0'};...
                  {'0','0.2','0.4','0.6','0.8','1.0'};...
                  {'0','0.2','0.4','0.6','0.8','1.0'};...
                  {};...
                  {'0','0.2','0.4','0.6','0.8','1.0'};...
                  {'1.0','3.0','5.0','7.0'};...
                  {'1.0','3.0','5.0','7.0'};...
                  {'1.0','3.0','5.0','7.0'};...
                  {'1.0','3.0','5.0','7.0'};...
                  {'0','0.2','0.4','0.6','0.8','1.0'};...
                  {'1.0','3.0','5.0','7.0'};...
                  {'1.0','3.0','5.0','7.0'};...
                  {'1.0','3.0','5.0','7.0'};...
                  {'1.0','3.0','5.0','7.0'};...
                  };
    %%% y-axis labels %%%
    ylabels = {'';...
               ' mRNA degradation';...
               ' mRNA degradation';...
               ' mRNA degradation';...
               '';...
               ' activation, 1\muM';...
               ' mRNA expression, 1\muM';...
               ' mRNA expression, 1\muM';...
               ' mRNA expression, 1\muM';...
               ' mRNA expression, 1\muM';...
               ' activation, 10\muM';...
               ' mRNA expression, 10\muM';...
               ' mRNA expression, 10\muM';...
               ' mRNA expression, 10\muM';...
               ' mRNA expression, 10\muM';...
               };
    Text  = {'';...
             'CYP3A4';...
             'CYP2C9';...
             'CYP2B6';...
             '';...
             'PXR';...
             'CYP3A4';...
             'CYP2C9';...
             'CYP2B6';...
             'MDR1';...
             'PXR';...
             'CYP3A4';...
             'CYP2C9';...
             'CYP2B6';...
             'MDR1';...
             };
    mcolors = {[];...
               [0 0 0];...
               [0 0 0];...
               [0 0 0];...
               [];...
               [0 0 1];...
               [0 0 1];...
               [0 0 1];...
               [0 0 1];...
               [0 0 1];...
               [1 0 0];...
               [1 0 0];...
               [1 0 0];...
               [1 0 0];...
               [1 0 0]
               };

    data = vertcat(data{:});
    stdev = vertcat(stdev{:});
    

    %%% PLOT %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  
    figlabs = {'','(A)','(B)','(C)','',...
               '(D)','(E)','(F)','(G)','(H)',...
               '(I)','(J)','(K)','(L)','(M)'};
    tiledplot = tiledlayout(3,5,'TileSpacing','Compact');
    set(gcf, 'Position',  [300, 100, 1300, 600]);
    mm = 0;
    for aa = 1:3
        for bb = 1:5
            mm = mm+1;
            ax(mm) = nexttile(mm);
            if ismember(mm,[1,5])
                set(ax(mm),'Visible','off');
            else
                set(ax(mm),...
                    'box','on',...
                    'XLim',[-0.05*max(timeXaxis{mm}) 1.05*max(timeXaxis{mm})],...
                    'XTick',timeXaxis{mm},...
                    'XTickLabel',timeXaxis{mm},...
                    'XTickLabelRotation',45,...
                    'YLim',YLims{mm},...
                    'YTick',YTick{mm},...
                    'YTickLabel',YTickLabel{mm},...
                    'FontSize',10);
                set(gca,'TickLength',[0.025, 0.01])
                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                hold on;
                %%% shaded area %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                outputvec = [];
                for jj = 1:5
                    for oo = 1:5
                        chains = load(strcat('./chains_',num2str(jj),'/chains_',num2str(oo),'.mat'));
                        chains = chains.chains(:,:);
                        for nn = size(chains,1)/2:size(chains,1)
                            if mod(nn,100)==0
                                output = model(chains(nn,:));
                                outputvec = [outputvec;output{mm}];
                            end
                        end
                    end
                end
                outputvecmin = min(outputvec,[],1);
                outputvecmax = max(outputvec,[],1);

                outputvec_025prc = prctile(outputvec,2.5,1);
                outputvec_975prc = prctile(outputvec,97.5,1);

                patch(ax(mm),[T{mm},fliplr(T{mm})],[outputvecmin,fliplr(outputvecmax)],mcolors{mm},'FaceAlpha',0.1,'EdgeColor',mcolors{mm},'EdgeAlpha',0.1);
                patch(ax(mm),[T{mm},fliplr(T{mm})],[outputvec_025prc,fliplr(outputvec_975prc)],mcolors{mm},'FaceAlpha',0.25,'EdgeColor',mcolors{mm},'EdgeAlpha',0.25);
                
                hold on;
                % plot(ax(mm),T{mm},outputvecmin,'Color',[mcolors{mm} 0.1],'LineWidth',0.1,'LineStyle','-')
                % plot(ax(mm),T{mm},outputvecmax,'Color',[mcolors{mm} 0.1],'LineWidth',0.1,'LineStyle','-')
                
                %%% maximum likelihood %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                MLpars = readmatrix('maxLikValues.txt');
                outputmaxlik = model(MLpars(2:end,2));
                plot(ax(mm),T{mm},outputmaxlik{mm},'Color',mcolors{mm},'LineWidth',1,'LineStyle','-')
                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                hold on;
                if ismember(mm,vars)
                    errorbar(time{mm},nanmean(data{mm},1),stdev{mm},... 
                        'Marker','diamond', ...
                        'MarkerSize',4,...
                        'MarkerEdgeColor',[0 0 0],...
                        'MarkerFaceColor','white',...
                        'LineStyle','none',...
                        'LineWidth',0.5,...
                        'Color',[0 0 0],...
                        'CapSize',4);
                end
                title(strcat('\rm',Text{mm},ylabels{mm}),'FontSize',10);
                text(0.9,0.9,figlabs{mm},...
                        'Units','Normalized',...
                        'HorizontalAlignment','center',...
                        'FontSize',10,...
                        'FontWeight','Normal');                    

            end
        end
    end
    xlabel(tiledplot,'Time (hours)','FontSize',14);
%     ylabel(tiledplot,'Fold change to corresponding control','FontSize',14);
    tiledplot.TileSpacing = 'compact';
    tiledplot.Padding = 'compact';


    %%% save figure %%%
    if ~exist('./figures', 'dir')
        mkdir('./figures')
    end
    savefig(strcat('figures/kinetics.fig'));
    exportgraphics(gcf,'figures/kinetics.png');
    % exportgraphics(gcf,'../../LaTeX/figures/kinetics.eps','ContentType','vector');
             

    %%% helper functions %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%% output of the model %%%
    function [output] = model(pars) 
    
        %%% degradation of protein mRNA %%%
        output{1} = [];
        output{2} = exp(-pars(5) .* T{2});
        output{3} = exp(-pars(7) .* T{3});
        output{4} = exp(-pars(9) .* T{4});
        output{5} = [];

        solution_l = ode23s(@ode,[0 tmax{1}],...
                               [0 1 1 1 1],...
                               [],...
                               pars,...
                               Rif{1});
        solution_h = ode23s(@ode,[0 tmax{2}],...
                               [0 1 1 1 1],...
                               [],...
                               pars,...
                               Rif{2}); 
        %%% mRNA kinetics for measured proteins %%%
        %%% low
        kk = 6;
        % pxr and enzymes
        for ii = 1:5
            output{kk} = deval(solution_l,T{kk},ii);
            kk = kk + 1;
        end
        %%% high
        % pxr and enzymes
        for ii = 1:5
            output{kk} = deval(solution_h,T{kk},ii);
            kk = kk + 1;
        end        
        
    end

    %%% ODE system %%%
    function [dxdt] = ode(t,x,pars,Xint)        
        dxdt = zeros(5,1);

        dxdt(1) = pars(1)*(1-x(1))*Xint*exp(-pars(2)*t) - pars(3)*x(1);    % activated PXR
        dxdt(2) = pars(4)*x(1) + pars(5)*(1-x(2));                         % CYP3A4
        dxdt(3) = pars(6)*x(1) + pars(7)*(1-x(3));                         % CYP2C9
        dxdt(4) = pars(8)*x(1) + pars(9)*(1-x(4));                         % CYP2B6
        dxdt(5) = pars(10)*x(1) + pars(11)*(1-x(5));                       % MDR1
    end

end