function [] = plot_data()

    %%% command:
    %%% plot_data()
   
    clc;
    close all;
    clear all;
    set(0,'DefaultFigureVisible','on');
        
    % load data and parameters
    metadata = load('datamat.mat');
    
    %%% CYPs %%%
    data = {metadata.data_deg;{[]};metadata.data_l;metadata.data_h};
    data = vertcat(data{:});
    time = {metadata.time_deg;...
            metadata.time_deg;...
            metadata.time_deg;...
            [];...
            metadata.time_l;...
            metadata.time_l;...
            metadata.time_l;...
            metadata.time_l;...
            metadata.time_h;...
            metadata.time_h;...
            metadata.time_h;...
            metadata.time_h;...
            };
    timeXaxis = {[0,12,24,36,48];...
                 [0,12,24,36,48];...
                 [0,12,24,36,48];...
                 [];...
                 [0,24,48,72,120,168];...
                 [0,24,48,72,120,168];...
                 [0,24,48,72,120,168];...
                 [0,24,48,72,120,168];...
                 [0,24,48,72,120,168,240];...
                 [0,24,48,72,120,168,240];...
                 [0,24,48,72,120,168,240];...
                 [0,24,48,72,120,168,240]};
    YLims = {[-0.15 1.15];...
             [-0.15 1.15];...
             [-0.15 1.15];...
             [];...
             [0.0 8];...
             [0.0 8];...
             [0.0 8];...
             [0.0 8];...
             [0.0 8];...
             [0.0 8];...
             [0.0 8];...
             [0.0 8]};    
    YTick = {0:0.2:1;...
             0:0.2:1;...
             0:0.2:1;...
             [];...
             1:2:7;...
             1:2:7;...
             1:2:7;...
             1:2:7;...
             1:2:7;...
             1:2:7;...
             1:2:7;...
             1:2:7};    
    YTickLabel = {{'0','0.2','0.4','0.6','0.8','1.0'};...
                  {'0','0.2','0.4','0.6','0.8','1.0'};...
                  {'0','0.2','0.4','0.6','0.8','1.0'};...
                  {};...
                  {'1.0','3.0','5.0','7.0'};...
                  {'1.0','3.0','5.0','7.0'};...
                  {'1.0','3.0','5.0','7.0'};...
                  {'1.0','3.0','5.0','7.0'};...
                  {'1.0','3.0','5.0','7.0'};...
                  {'1.0','3.0','5.0','7.0'};...
                  {'1.0','3.0','5.0','7.0'};...
                  {'1.0','3.0','5.0','7.0'}};
    %%% y-axis labels %%%
    ylabels = {' mRNA degradation';...
               ' mRNA degradation';...
               ' mRNA degradation';...
               '';...
               ' mRNA expression, 1\muM';...
               ' mRNA expression, 1\muM';...
               ' mRNA expression, 1\muM';...
               ' mRNA expression, 1\muM';...
               ' mRNA expression, 10\muM';...
               ' mRNA expression, 10\muM';...
               ' mRNA expression, 10\muM';...
               ' mRNA expression, 10\muM'};
    Text  = {'CYP3A4';...
             'CYP2C9';...
             'CYP2B6';...
             '';...
             'CYP3A4';...
             'CYP2C9';...
             'CYP2B6';...
             'MDR1';...
             'CYP3A4';...
             'CYP2C9';...
             'CYP2B6';...
             'MDR1'};
    
    %%%% Each donor in different color %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    facecol = {'red','blue','green'};
    names = {'Donor 1','Donor 2','Donor 3'};
    markers = {'o','diamond','square'};
    figlabs = {'(a)','(b)','(c)','','(d)','(e)','(f)','(g)','(h)','(i)','(j)','(k)'};
    markersize = 30;
    markerfa = {0.5,0.5,0.5};
    mcolors = [0 0 0];
    
    figure(1);
    clc;
    tiledplot = tiledlayout(3,4);
    set(gcf, 'Position',  [500, 100, 1200, 700]);
    clc;
    mm = 0;
    for aa = 1:3
        for bb = 1:4
            mm = mm+1;
            ax(mm) = nexttile(mm);
            if mm == 4
                set(ax(mm),'Visible','off');
            else
                set(ax(mm),...
                    'box','on',...
                    'XLim',[-0.05*max(timeXaxis{mm}) 1.05*max(timeXaxis{mm})],...
                    'XTick',timeXaxis{mm},...
                    'XTickLabel',timeXaxis{mm},...
                    'XTickLabelRotation',45,...
                    'YLim',YLims{mm},...
                    'YTick',YTick{mm},...
                    'YTickLabel',YTickLabel{mm},...
                    'FontSize',10);
                set(gca,'TickLength',[0.025, 0.01])
                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                hold on;
                %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                for kk = 1:size(data{mm},1)
                    scatter(time{mm},data{mm}(kk,:),markersize,... 
                        'Marker',markers{kk}, ...
                        'MarkerEdgeColor',mcolors,...
                        'MarkerFaceColor',facecol{kk},...
                        'MarkerFaceAlpha',markerfa{kk});
                end
                hold off;
                title(strcat('\rm',Text{mm},ylabels{mm}),'FontSize',10);
                text(0.9,0.9,figlabs{mm},...
                        'Units','Normalized',...
                        'HorizontalAlignment','center',...
                        'FontSize',10,...
                        'FontWeight','Normal');                    
            end
        end
    end
    leg = legend(ax(1),names,'Location','SouthOutside','FontSize',10,'Orientation','Horizontal');
    leg.Layout.Tile = 'North';
    xlabel(tiledplot,'Time (hours)','FontSize',14);
    ylabel(tiledplot,'Fold change to corresponding control','FontSize',14);
    tiledplot.TileSpacing = 'compact';
    tiledplot.Padding = 'compact';

    %%% save figure %%%
    if ~exist('./figures', 'dir')
        mkdir('./figures')
    end
    savefig(strcat('figures/data.fig'));
    exportgraphics(gcf,'figures/data.png');
    % exportgraphics(gcf,'../../LaTeX/figures/data.eps','ContentType','vector');
            
    end